[workspace]
name = "brainprep"
version = "2.0.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "==3.12"

[pypi-dependencies]
brainprep = { git = "https://github.com/neurospin-deepinsight/brainprep.git", branch = "dev" }

