import xml.etree.ElementTree as ET
import pandas as pd

from brainprep.utils.utils import parse_bids_keys



def get_cat12_total_volumes(report_xml_file):
    """ Parse the report/*.xml file generated by cat12vbm to get the total 
    volumes (TIV, total volumes of GM, WM and CSF) of the associated subject.
    
    Arguments
    ---------
    report_xml_file: str or Path
        xml file to parse. The relevant information is supposed to be in
        the 'subjectmeasures' subsection.

    Returns
    -------
    total_volumes: pandas dataframe
        Dataframe containing the subjects BIDS keys and total brain volumes.
    """
    tree = ET.parse(report_xml_file)
    root = tree.getroot()
    subjectmeasures = root.find('subjectmeasures')

    # get tiv
    tiv = float(subjectmeasures.find("vol_TIV").text)
    # get tissue volumes
    tissue_volumes = subjectmeasures.find("vol_abs_CGW").text
    tissue_volumes = tissue_volumes.strip('[]').split(' ')[:3]

    # group all the volumes in a dataframe
    volumes = {'tiv': [tiv],
               'CSF_Vol': [float(tissue_volumes[0])],
               'GM_Vol': [float(tissue_volumes[1])],
               'WM_Vol': [float(tissue_volumes[2])]}
    total_volumes = pd.DataFrame(volumes)

    # add the bids keys
    bids_keys = parse_bids_keys(report_xml_file)
    bids_keys_df = pd.DataFrame(
        {'participant_id': [bids_keys['sub']],
         'session': [bids_keys['ses']],
         'run': [bids_keys['run']],}
    )
    total_volumes = pd.concat([bids_keys_df, total_volumes], axis=1)

    return total_volumes


def flatten_roi_volumes(roi_volumes):
    """ Transform the pandas dataframe with one row per brain tissue to a 
    dataframe with only one row. Relabel the columns with suffixes to avoid 
    ambiguities.
    
    Arguments
    ---------
    roi_volumes: pandas dataframe
        Dataframe containing roi volumes data. It has one row per brain tissue 
        and one column per brain region.
    
    Returns
    -------
    flattened_roi_volumes: pandas dataframe
        Dataframe containing the same information as roi_volumes, but with 
        only one row. Each column is labeled as <roi_name>_<tissue_name>_Vol.
    """
    # define the columns names
    flatten_region_names = []
    for brain_tissue in roi_volumes.index.values:
        tissue_name = brain_tissue[1:].upper()
        flatten_region_names.extend([col+f'_{tissue_name}_Vol' 
                                     for col in roi_volumes.columns])
    # flatten the data
    data = roi_volumes.values.flatten()
    # create a new flattened dataframe
    flattened_roi_volumes = pd.DataFrame(data.reshape(1,data.shape[0]),
                                         columns=flatten_region_names)
    return flattened_roi_volumes


def get_cat12_roi_volumes(label_xml_file, atlas_name='neuromorphometrics'):
    """ Parse the label/catROI*.xml file generated by cat12vbm to get each 
    brain tissue volume (GM, WM, CSF) per brain region for a given subject.
    
    Arguments
    ---------
    label_xml_file: str or Path
        xml file to parse.

    Returns
    -------
    roi_volumes: pandas dataframe
        Dataframe containing the subjects BIDS keys and roi tissue volumes.
    """
    # parse the label xml to find the given atlas
    tree = ET.parse(label_xml_file)
    root = tree.getroot()
    atlas = root.find(atlas_name)

    # get the region names
    region_names = [item.text for item in atlas.find("names").findall("item")]

    # get the actual data
    roi_volumes = {}
    data = atlas.find("data")
    for brain_region in data:
        tissue_data = [float(x) for x in brain_region.text.strip("[]").split(';')]
        roi_volumes[brain_region.tag] = tissue_data
    # convert to a dataframe with only one row
    roi_volumes = pd.DataFrame(roi_volumes, index=region_names)
    roi_volumes = roi_volumes.transpose()
    roi_volumes = flatten_roi_volumes(roi_volumes)

    # add the bids keys
    bids_keys = parse_bids_keys(label_xml_file)
    bids_keys_df = pd.DataFrame(
        {'participant_id': [bids_keys['sub']],
         'session': [bids_keys['ses']],
         'run': [bids_keys['run']],}
    )
    roi_volumes = pd.concat([bids_keys_df, roi_volumes], axis=1)

    return roi_volumes


def parse_cat12vbm_roi(report_xml_files: list, label_xml_files: list,
                       atlas_name="neuromorphometrics"):
    """ Parse provided cat12 xml files for a given atlas.

    Arguments
    ---------
    report_xml_files: list
        List of the "report" cat12 xml files, i.e. the ones whose path is like
        <sub_cat12dir>/report/cat*.xml.
    label_xml_files: list
        List of the "label" cat12 xml files, i.e. the ones whose path is like
        <sub_cat12dir>/label/catROI*.xml.
    atlas_name: str
        Name of the atlas used to define the ROI. It should be a element of the
        "label" xml files.
    
    Returns
    -------
    cat12_roi: pandas dataframe
        Dataframe containing total and per roi brain tissue volumes for each 
        given cat12 output.
    """
    # parse all subjects' report xml
    total_volumes = pd.DataFrame()
    for report_file in report_xml_files:
        sub_vol = get_cat12_total_volumes(report_file)
        total_volumes = pd.concat([total_volumes, sub_vol], axis=0,
                                  ignore_index=True)
    # parse all subjects' label xml
    roi_volumes = pd.DataFrame()
    for label_file in label_xml_files:
        sub_vol = get_cat12_roi_volumes(label_file, atlas_name=atlas_name)
        roi_volumes = pd.concat([roi_volumes, sub_vol], axis=0,
                                ignore_index=True)
    # merge the dataframes
    bids_cols = ['participant_id', 'session', 'run']
    cat12_roi = pd.merge(total_volumes, roi_volumes, how='outer', on=bids_cols)
    cat12_roi = cat12_roi.sort_values(by=bids_cols)

    return cat12_roi
