##########################################################################
# NSAp - Copyright (C) CEA, 2021 - 2025
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

"""
Functions for running shell commands
"""

import inspect
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Optional, Union

from decorator import decorator

from .config import (
    DEFAULT_OPTIONS,
    brainprep_options,
)
from .utils import (
    print_command,
    print_error,
    print_info,
    print_result,
)


@decorator
def pywrapper(
        func: Callable,
        *args,
        **kw) -> Optional[tuple[str]]:
    """
    Decorator that executes a Python function with injected dryrun options.

    Parameters
    ----------
    func : callable
        The function to be decorated. It should accept a 'dryrun' argument.
    *args : tuple
        Positional arguments passed to `func`.
    **kw : dict
        Keyword arguments passed to `func`.

    Returns
    -------
    outputs : outputs
        The list of output files if provided by the decorated function,
        otherwise None.

    Raises
    ------
    ValueError
        If the decorated function returns an invalid value or the `dryrun`
        keyword argument is not defined.
    FileNotFoundError
        If any expected output file is missing.

    Notes
    -----
    - Check that the function outputs are valid.

    Example
    -------
    >>> @pywrapper
    ... def ls_command(my_dir, dryrun=False):
    ...     if dryrun:
    ...         return None
    ...     return os.listdir(my_dir)
    >>> with Config(dryrun=True):
    ...     ls_command("/tmp")
    None
    """
    opts = brainprep_options.get()
    verbose = opts.get("verbose", DEFAULT_OPTIONS["verbose"])
    dryrun = opts.get("dryrun", DEFAULT_OPTIONS["dryrun"])
    inputs = inspect.getcallargs(func, *args, **kw)
    if "dryrun" not in inputs:
        raise ValueError(
            "This decorator needs a 'dryrun' function argument."
        )

    inputs["dryrun"] = dryrun
    outputs = func(**inputs)

    for item in outputs or []:
        _check_outputs(item, dryrun, verbose)

    if outputs is None:
        return None
    elif len(outputs) == 1:
        return outputs[0]
    else:
        return tuple(outputs)


@decorator
def cmdwrapper(
        func: Callable,
        *args,
        **kw) -> Optional[tuple[str]]:
    """
    Executes a command-line instruction generated by the decorated function.

    Parameters
    ----------
    func : callable
        The function to be decorated. It should return either:
        - A command-line to execute, or
        - A tuple containing the command-lines and a list of expected output
          files.
    *args : tuple
        Positional arguments passed to `func`.
    **kw : dict
        Keyword arguments passed to `func`.

    Returns
    -------
    outputs : outputs
        The list of output files if provided by the decorated function,
        otherwise None.

    Raises
    ------
    ValueError
        If the decorated function returned value is incorrect, the command
        format is invalid, the platform is not Linux, or the command is not
        found.
    RuntimeError
        If the command execution fails or produces no output.
    FileNotFoundError
        If any expected output file is missing.

    Notes
    -----
    - A list of commands is authrized.
    - Check that the function outputs are valid.

    Example
    -------
    >>> @cmdwrapper
    ... def ls_command(my_dir):
    ...     return ["ls", "-l", my_dir]
    >>> ls_command("/tmp")
    """
    opts = brainprep_options.get()
    verbose = opts.get("verbose", DEFAULT_OPTIONS["verbose"])
    dryrun = opts.get("dryrun", DEFAULT_OPTIONS["dryrun"])

    return_values = func(*args, **kw)
    if isinstance(return_values, list):
        command, outputs = return_values, None
    elif isinstance(return_values, tuple) and len(return_values) == 2:
        command, outputs = return_values
    else:
        raise ValueError(
            "The decorated function must return either a command list, "
            "or a tuple of (command list, (output files, ))."
        )

    if not _is_list_str(command) and not _is_list_list_str(command):
        raise ValueError(
            "Invalid command format: expected a list of strings or a list of "
            "list of string for multiple commands."
        )
    commands = [command] if _is_list_str(command) else command
    for cmd in commands:
        print_command(" ".join(cmd))

    if not dryrun:
        for cmd in commands:
            is_command_installed(cmd[0])
            process = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = process.communicate()
            if process.returncode != 0:
                print_info(stdout.decode("utf-8"))
                print_error(stderr.decode("utf-8"))
                raise RuntimeError(
                    f"Command execution failed: {' '.join(cmd)}"
                )

    for item in outputs or []:
        _check_outputs(item, dryrun, verbose)

    if outputs is None:
        return None
    elif len(outputs) == 1:
        return outputs[0]
    else:
        return tuple(outputs)


def _is_list_str(
        command: Any) -> bool:
    return (isinstance(command, list) and
            all(isinstance(item, str) for item in command))


def _is_list_list_str(
        command: Any) -> bool:
    return (isinstance(command, list) and
            all(_is_list_str(item) for item in command))


def _check_outputs(
        item: Union[str, Path, list[str], list[Path], tuple[str], tuple[Path]],
        dryrun: bool = False,
        verbose: bool = False) -> None:
    """
    Recursively validates output file paths.

    Parameters
    ----------
    item : str, Path, list, or tuple
        A single file path or a collection of paths to validate.
    dryrun : bool, default False
        If True, skips file existence checks.
    verbose : bool, default False
        If True, prints each path being checked.

    Raises
    ------
    FileNotFoundError
        If `dryrun` is False and any specified path does not exist.
    ValueError
        If the input is neither a path nor a list/tuple of paths.
    """
    if isinstance(item, (list, tuple)):
        for subitem in item:
            _check_outputs(subitem, dryrun, verbose)
    elif isinstance(item, (str, Path)):
        path = Path(item)
        print_info(f"checking output: {path}")
        if not dryrun and not path.exists():
            raise FileNotFoundError(
                f"Output file/directory not found: {path}"
            )
    else:
        raise ValueError(
            "The ouputs must be either a path or a list/tuple of paths."
        )


def is_command_installed(command: str):
    """
    Verifies if a command is installed on a Linux system using the `which`
    utility.

    Parameters
    ----------
    command: str
        The name of the command to locate.

    Raises
    ------
    ValueError
        If the platform is not Linux or the command cannot be found.
    """
    if sys.platform != "linux":
        raise ValueError("This function is supported only on Linux systems.")

    process = subprocess.Popen(
        ["which", command], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()

    if process.returncode != 0:
        print_info(stdout.decode("utf-8"))
        print_error(stderr.decode("utf-8"))
        raise ValueError(f"Unable to locate command: {command}")
