##########################################################################
# NSAp - Copyright (C) CEA, 2021 - 2025
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

"""
Functions for running shell commands
"""

from typing import Any, Callable, Optional, Union

import contextvars
import inspect
import os
import subprocess
import sys
from decorator import decorator
from pathlib import Path
from .utils import (
    print_command,
    print_error,
    print_info,
    print_result,
)


DEFAULT_OPTIONS = {
    "verbose": True,
    "dryrun": False
}

cmdwrapper_options = contextvars.ContextVar(
    "cmdwrapper_options",
    default=DEFAULT_OPTIONS,
)


@decorator
def pywrapper(
        func: Callable,
        *args,
        **kw) -> Optional[tuple[str]]:
    """
    Decorator that executes a Python function with injected dryrun options.

    Parameters
    ----------
    func : callable
        The function to be decorated. It should accept a 'dryrun' argument.
    *args : tuple
        Positional arguments passed to `func`.
    **kw : dict
        Keyword arguments passed to `func`.

    Returns
    -------
    outputs : outputs
        The list of output files if provided by the decorated function,
        otherwise None.

    Raises
    ------
    ValueError
        If the decorated function returns an invalid value. or the `dryrun`
        keyword argument is not defined.
    FileNotFoundError
        If any expected output file is missing.

    Example
    -------
    >>> @pywrapper
    ... def ls_command(my_dir, dryrun=False):
    ...     if dryrun:
    ...         return None
    ...     return os.listdir(my_dir)
    >>> with WrapperConfig(dryrun=True):
    ...     ls_command("/tmp")
    None
    """
    opts = cmdwrapper_options.get()
    verbose = opts.get("verbose", DEFAULT_OPTIONS["verbose"])
    dryrun = opts.get("dryrun", DEFAULT_OPTIONS["dryrun"])
    inputs = inspect.getcallargs(func, *args, **kw)
    if "dryrun" not in inputs:
        raise ValueError(
            f"This decorator needs a 'dryrun' function argument."
        )

    inputs["dryrun"] = dryrun
    outputs = func(**inputs)

    if outputs is not None and not isinstance(outputs, (list, tuple)):
        raise ValueError(
            "Function must return a list or tuple of output paths, or None."
        )

    for path in outputs or []:
        if verbose:
            print_result(path)
        if not dryrun and not os.path.isfile(path):
            raise FileNotFoundError(
                f"Output file not found: {path}"
            )

    return outputs


@decorator
def cmdwrapper(
        func: Callable,
        *args,
        **kw) -> Optional[tuple[str]]:
    """
    Executes a command-line instruction generated by the decorated function.

    Parameters
    ----------
    func : callable
        The function to be decorated. It should return either:
        - A command-line to execute, or
        - A tuple containing the command-lines and a list of expected output
          files.
    *args : tuple
        Positional arguments passed to `func`.
    **kw : dict
        Keyword arguments passed to `func`.

    Returns
    -------
    outputs : outputs
        The list of output files if provided by the decorated function,
        otherwise None.

    Raises
    ------
    ValueError
        If the decorated function returned value is incorrect, the command
        format is invalid, the platform is not Linux, or the command is not
        found.
    RuntimeError
        If the command execution fails or produces no output.
    FileNotFoundError
        If any expected output file is missing.

    Example
    -------
    >>> @cmdwrapper
    ... def ls_command(my_dir):
    ...     return ["ls", "-l", my_dir]
    >>> ls_command("/tmp")
    """
    opts = cmdwrapper_options.get()
    verbose = opts.get("verbose", DEFAULT_OPTIONS["verbose"])
    dryrun = opts.get("dryrun", DEFAULT_OPTIONS["dryrun"])

    return_values = func(*args, **kw)
    if isinstance(return_values, list):
        command, outputs = return_values, None
    elif isinstance(return_values, tuple) and len(return_values) == 2:
        command, outputs = return_values
    else:
        raise ValueError(
            "The decorated function must return either a command list, "
            "or a tuple of (command list, (output files, ))."
        )

    if (not isinstance(command, list) or
            not all([isinstance(item, str) for item in command])):
        raise ValueError(
            "Invalid command format: expected a list of strings."
        )
    if verbose:
        print_command(" ".join(command))

    if not dryrun:
        is_command_installed(command[0])
        process = subprocess.Popen(
            command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
        if process.returncode != 0:
            if verbose:
                print_info(stdout.decode("utf-8"))
                print_error(stderr.decode("utf-8"))
            raise RuntimeError(
                f"Command execution failed: {' '.join(command)}"
            )

    for item in outputs or []:
        _check_outputs(item, dryrun, verbose)

    if outputs is None:
        return None
    elif len(outputs) == 1:
        return outputs[0]
    else:
        return tuple(outputs)


def _check_outputs(
        item: Union[str, Path, list[str], list[Path], tuple[str], tuple[Path]],
        dryrun: bool = False,
        verbose: bool = False) -> None:
    """
    Recursively validates output file paths.

    Parameters
    ----------
    item : str, Path, list, or tuple
        A single file path or a collection of paths to validate.
    dryrun : bool, default False
        If True, skips file existence checks.
    verbose : bool, default False
        If True, prints each path being checked.

    Raises
    ------
    FileNotFoundError
        If `dryrun` is False and any specified path does not exist.
    ValueError
        If the input is neither a path nor a list/tuple of paths.
    """
    if isinstance(item, (list, tuple)):
        for subitem in item:
            _check_outputs(subitem, dryrun, verbose)
    elif isinstance(item, (str, Path)):
        path = Path(item)
        if not dryrun and not path.exists():
            raise FileNotFoundError(
                f"Output file/directory not found: {path}"
            )
    else:
        raise ValueError(
            "The ouputs must be either a path or a list/tuple of paths."
        )


class WrapperConfig:
    """
    Context manager for modifying options passed to
    :func:`~brainprep.interfaces.wrappers.cmdwrapper` when executing
    commands from decorated functions.

    Parameters
    ----------
    **options : dict
        Keyword arguments intercepted by the wrapper function:
        - verbose : bool, default True - print informations or not.
        - dryrun : bool, default False - execute commands or not

    Example
    -------
    >>> with WrapperConfig(dryrun=True):
    ...     brainprep_deface('t1w.nii.gz', '/tmp')

    Notes
    -----
    - The context variable `cmdwrapper_options` holds the current
      configuration.
    - Options are scoped to the `with` block and automatically restored
      afterward.
    """
    def __init__(self, **options):
        self.token = None
        self.options = options

    def __enter__(self):
        self.token = cmdwrapper_options.set(self.options)

    def __exit__(self, exc_type, exc_val, exc_tb):
        cmdwrapper_options.reset(self.token)


def is_command_installed(command: str):
    """
    Verifies if a command is installed on a Linux system using the `which`
    utility.

    Parameters
    ----------
    command: str
        The name of the command to locate.

    Raises
    ------
    ValueError
        If the platform is not Linux or the command cannot be found.
    """
    if sys.platform != "linux":
        raise ValueError("This function is supported only on Linux systems.")

    process = subprocess.Popen(
        ["which", command], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()

    if process.returncode != 0:
        print_info(stdout.decode("utf-8"))
        print_error(stderr.decode("utf-8"))
        raise ValueError(f"Unable to locate command: {command}")
