"""
fMRI Pre-Processings
====================

Simple example.

Example on how to run the dMRI pre-processing using BrainPrep.
See :ref:`user guide <dmriprep>` for details.

Data
----

Let's first get some anatomical/diffusion data.
"""

from pathlib import Path
from brainprep.datasets import MultiModalDataset

datadir = Path("/tmp/brainprep-data")
datadir.mkdir(parents=True, exist_ok=True)
dataset = MultiModalDataset(datadir)
data = dataset.fetch(
    subject="01",
    modality="dwi",
    session="01",
)
print(data)


# %%
# Analysis
# --------
# 
# Let's now perform the preprocessing using BrainPrep.
# As with many tutorials, we won't execute the code directly here.
# However, feel free to set the 'dryrun' configuration to False
# to actually run each step and generate results on disk.


from brainprep.workflow import (
    brainprep_dmriprep,
    brainprep_group_dmriprep,
)
from brainprep.config import Config
from brainprep.reporting import RSTReport

outdir = Path("/tmp/brainprep-dmriprep")
outdir.mkdir(parents=True, exist_ok=True)
with Config(dryrun=True, verbose=True):
    report = RSTReport()
    brainprep_dmriprep(
        t1_file=data.anat,
        dwi_file=data.dwi,
        bvec_file=data.bvec,
        bval_file=data.bval,
        output_dir=outdir,
        keep_intermediate=True,
    )
    print(report)
    brainprep_group_dmriprep(
        output_dir=outdir,
    )


# %%
# CLI
# ---
# 
# Let's now generate the same analysis using the CLI. The goal here is to
# translate the workflow calls into explicit shell commands.
# See :ref:`user guide <cli>` for details.

from pprint import pprint

commands = []
commands.append(
    [
        [
            "brainprep", "subject-level-dmriprep",
            "--t1-file", str(data.anat),
            "--dwi-file", str(data.dwi),
            "--bvec-file", str(data.bvec),
            "--bval-file", str(data.bval),
            "--output-dir", str(outdir),
            "--keep-intermediate",
        ]
    ]
)
commands.append(
    [
        [
            "brainprep", "group-level-dmriprep",
            "--output-dir", str(outdir),
        ]
    ]
)
pprint(commands)


# %%
# Container
# ---------
# 
# Note that the commands generated by the CLI are not limited to being
# displayed for reference; they can also be executed directly within the
# workflow‑dedicated container. By running the commands inside the container,
# you benefit from a controlled runtime context where all necessary
# dependencies, libraries, and configuration files are already available.
# In practice, this means that once the CLI has produced the appropriate
# instructions, you can simply copy and run them inside the container to
# achieve the intended results. You can find the BrainPrep images on Docker
# Hub: `Neurospin Docker Hub <https://hub.docker.com/u/neurospin>`_.
